//
// Created by larox on 20.06.19.
//

#ifndef UBIRCH_ENERTHING_FIRMWARE_LIS2DH12_H
#define UBIRCH_ENERTHING_FIRMWARE_LIS2DH12_H

#include "lis2dh12_reg.h"

#endif //UBIRCH_ENERTHING_FIRMWARE_LIS2DH12_H
